### ISSUE TITLE
Papse error in fresh install of Pico Version 1.0.2

### ISSUE THREAD

**Issue by epigraphe** [PontusHorn/Pico-Tags#1]
Good afternoon. I just downloaded and installed the Pico, copied plugin in a directory and when i try to open the site get this error.

Parse error: syntax error, unexpected '[' in Z:\home\localhost\www\plugins\PicoTags.php on line 90

If I remove the plugin - it works.

**Comment by PontusHorn** [comment]
Hi! That happens because you're using PHP version 5.3 or lower. The short array syntax was introduced in 5.4, and that's what the parser is stumbling on. I've committed a fix that should help you avoid the issue, but generally speaking I wouldn't expect libraries to stay compatible with PHP 5.3.

I'd strongly advise you to upgrade to version 5.6, if that's at all possible for you. 5.3 reached end of life status back in 2014, meaning it hasn't received any security updates or fixes at all since then.
